spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal

apikey:
  weather: your_weather_api_key_here
