spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

apikey:
  weather: your_weather_api_key_here
